all:
	g++ -std=c++11 -Wall main.cpp Aluno.cpp Exercicio.cpp Cardio.cpp Forca.cpp Ficha.cpp -o academia

clean:
	rm -f academia *.o

run:
	g++ -std=c++11 -Wall main.cpp Aluno.cpp Exercicio.cpp Cardio.cpp Forca.cpp Ficha.cpp -o academia && ./academia
